version = 0.1

[1]
[1.global]
[1.global.parameters]
stack_name = "sam-prod"
s3_prefix = "sam-prod"
s3_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-8ixqfvfmufio"
region = "us-east-1"
image_repository = "273354638471.dkr.ecr.us-east-1.amazonaws.com/aws-sam-cli-managed-prod-pipeline-resources-imagerepository-x2hyvuxrdiry"

[1.deploy]
[1.deploy.parameters]
template = "packaged-prod.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""

# ############################################## #

[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "pipeline-stack"
s3_prefix = "pipeline-stack"
resolve_s3 = true
fail_on_empty_changeset = false
template = "codepipeline.yaml"
capabilities = "CAPABILITY_IAM"
